import { NextRequest } from 'next/server';
import path from 'path';
import fs from 'fs';

const ARTIFACT_DIR = path.join(process.cwd(), 'data', 'artifacts');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.pdf': 'application/pdf',
  '.md': 'text/markdown',
  '.txt': 'text/plain',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  const { path: pathParts } = await params;
  const resolvedDir = path.resolve(ARTIFACT_DIR);
  const filePath = path.resolve(ARTIFACT_DIR, ...pathParts);

  // Boundary check: the resolved path must be the dir itself or strictly below it.
  // Comparing with `resolvedDir + path.sep` prevents the "/artifacts_evil" bypass.
  if (filePath !== resolvedDir && !filePath.startsWith(resolvedDir + path.sep)) {
    return new Response('Forbidden', { status: 403 });
  }

  if (!fs.existsSync(filePath)) {
    const fileName = pathParts[pathParts.length - 1];
    return new Response(
      `<!DOCTYPE html>
<html><head><title>${fileName}</title>
<style>body{background:#0a0a0f;color:#e8e8ef;font-family:system-ui;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;}
.c{text-align:center;max-width:500px;padding:2rem;}h1{font-size:1.25rem;margin-bottom:0.5rem;}p{color:#9898a8;font-size:0.875rem;}</style>
</head><body><div class="c"><h1>${fileName}</h1><p>This artifact will be available once generated by the agent system. The file has not been created yet.</p></div></body></html>`,
      { headers: { 'Content-Type': 'text/html' } }
    );
  }

  const ext = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[ext] || 'application/octet-stream';
  const content = fs.readFileSync(filePath);

  return new Response(content, {
    headers: { 'Content-Type': contentType },
  });
}
